# Generated by Django 3.1.2 on 2020-10-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(null=True)),
                ('title', models.CharField(max_length=256)),
                ('isbn_number', models.CharField(max_length=17, null=True)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('partial_date', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='books.Author')),
            ],
        ),
    ]
